/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KEYWORD = 5;
  /** RegularExpression Id. */
  int ADDOP = 6;
  /** RegularExpression Id. */
  int MULTOP = 7;
  /** RegularExpression Id. */
  int ASSIGNOP = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int OPENPAREN = 10;
  /** RegularExpression Id. */
  int CLOSEPAREN = 11;
  /** RegularExpression Id. */
  int BEGIN = 12;
  /** RegularExpression Id. */
  int END = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;
  /** RegularExpression Id. */
  int LETTER = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<KEYWORD>",
    "<ADDOP>",
    "<MULTOP>",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
